Repository CS2113-AY1819S1-W12-4/main, pull requests merged in 2018-10, with the labels that each got.

#36 Adding of Batch List and Class
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/drink/Batch.java
  src/main/java/seedu/address/model/drink/BatchDate.java
  src/main/java/seedu/address/model/drink/BatchId.java
  src/main/java/seedu/address/model/drink/BatchPrice.java
  src/main/java/seedu/address/model/drink/BatchQuantity.java
  src/main/java/seedu/address/model/drink/Price.java
  src/main/java/seedu/address/model/drink/UniqueBatchList.java
  src/main/java/seedu/address/model/drink/exceptions/BatchNotFoundException.java
  src/main/java/seedu/address/model/drink/exceptions/DuplicateBatchException.java
  src/main/java/seedu/address/model/drink/exceptions/EmptyBatchListException.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  test/java/seedu/address/model/drink/BatchDateTest.java
  test/java/seedu/address/model/drink/UniqueBatchListTest.java
Labels: priority.high, type.task

#76 Update login function
  build.gradle
  loginInfoManager.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/authentication/AuthenticationLevelConstant.java
  src/main/java/seedu/address/authentication/PasswordUtils.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/LoginInfo.java
  src/main/java/seedu/address/commons/events/model/InitInventoryListEvent.java
  src/main/java/seedu/address/controller/LoginController.java
  src/main/java/seedu/address/init/InitAddressBook.java
  src/main/java/seedu/address/logic/commands/user/ChangePasswordCommand.java
  src/main/java/seedu/address/logic/commands/user/CreateAccountCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/user/AdminParser.java
  src/main/java/seedu/address/logic/parser/user/ChangePasswordCommandParser.java
  src/main/java/seedu/address/logic/parser/user/CreateAccountCommandParser.java
  src/main/java/seedu/address/logic/parser/user/StockTakerParser.java
  src/main/java/seedu/address/model/LoginInfoManager.java
  src/main/java/seedu/address/model/user/AuthenticationLevel.java
  src/main/java/seedu/address/model/user/Password.java
  src/main/java/seedu/address/model/user/UserName.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/PasswordUtilsTest.java
  src/test/java/seedu/address/model/UserNameTest.java
  unusedCode/tianhang/authenication/AuthenticationLevel.java
  unusedCode/tianhang/check/UserAuthenticationCheck.java
  unusedCode/tianhang/check/UserAuthenticationCheckUtils.java
Labels: status.ongoing

#91 Fix a bug that cause multiple instance of event after logout login
  loginInfoList.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/logic/LogicChangedEvent.java
  src/main/java/seedu/address/commons/events/model/ChangeModelEvent.java
  src/main/java/seedu/address/commons/events/ui/NewResultAvailableEvent.java
  src/main/java/seedu/address/commons/events/ui/RestartUiEvent.java
  src/main/java/seedu/address/controller/LoginController.java
  src/main/java/seedu/address/init/InventoryListInitializer.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/user/ManagerParser.java
  src/main/java/seedu/address/logic/parser/user/StockTakerParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: type.bug
